---
title: "Triangular Plot"
author: "Baoxing Liu"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r}
# Define the x-values (y) from 0 to 10
y <- 0:10

# Define the probability values (Probab(y)) for each 'h' value.
# The values appear to be manually defined or generated by a specific formula not specified in the image.
probs_h1_12 <- c(0, 0, 0, 0, 0, 0.083, 0.083, 0, 0, 0, 0)
probs_h1_2 <- c(0, 0, 0, 0, 0.083, 0.291, 0.083, 0, 0, 0, 0)
probs_h1 <- c(0, 0, 0, 0.083, 0.166, 0.666, 0.166, 0.083, 0, 0, 0)
probs_h2 <- c(0, 0.083, 0.125, 0.145, 0.156, 0.156, 0.156, 0.145, 0.125, 0.083, 0) # Approximate values based on visual representation
probs_h12 <- c(0, 0.104, 0.111, 0.111, 0.111, 0.111, 0.111, 0.111, 0.111, 0.104, 0) # Approximate values based on visual representation

# Create a data frame (or matrix) to store all the probability values
plot_data <- data.frame(y, probs_h1_12, probs_h1_2, probs_h1, probs_h2, probs_h12)

# Set up the plotting area, define limits and labels

plot(y, probs_h1_12, type = "n",
     ylim = c(0, 0.7), xlim = c(0, 10),
     xlab = "y", ylab = "Probab(y)",
     main = "Discrete Triangular Distribution")

# Add lines and points for each 'h' value, specifying different point types (pch) and line types (lty)
lines(y, probs_h1_12, type = "b", pch = 2, lty = 1) # h=1/12 (solid triangle)
lines(y, probs_h1_2, type = "b", pch = 6, lty = 1)  # h=1/2 (inverted solid triangle)
lines(y, probs_h1, type = "b", pch = 17, lty = 1)  # h=1 (solid triangle fillable)
lines(y, probs_h2, type = "b", pch = 1, lty = 2)   # h=2 (hollow circle, dashed line)
lines(y, probs_h12, type = "b", pch = 1, lty = 2)  # h=12 (hollow circle, dashed line)

# Add a legend to the top right corner

legend("topright",
       legend = c("h=1/12", "h=1/2", "h=1", "h=2", "h=12"),
       pch = c(2, 6, 17, 1, 1),
       lty = c(1, 1, 1, 2, 2),
       col = c("black", "black", "black", "black", "black"),
       bty = "n") # Removes the box around the legend
```

```{r}
discrete_triang_kernel <- function(xi, x, h, a) {
  num <- (a + 1)^h - abs(xi - x)^h
  num[num < 0] <- 0
  P_ah <- (2 * a + 1) * (a + 1)^h - 2 * sum((0:a)^h)
  return(num / P_ah)
}

a = 4
c = 5
xi = 0:10
h_grid = c(100,10,2,1,1/2,1/10,1/100)

Pr = list()
for (i in seq_along(h_grid)) {
  h = h_grid[i]
  Pr[[i]] = discrete_triang_kernel(xi, c, h, a)
}



png("tall_plot.png", width = 1000, height = 1200)
par(mar = c(5, 5, 3, 2))
plot(xi, Pr[[1]], type = "n",
     ylim = c(0, 1), xlim = c(0, 10),
     xlab = "y", ylab = "Probab(y)",
     main = "Discrete Triangular Distribution")
lines(xi, Pr[[1]], type = "b", pch = 1, lty = 1)
lines(xi, Pr[[2]], type = "b", pch = 2, lty = 2)
lines(xi, Pr[[3]], type = "b", pch = 3, lty = 3)
lines(xi, Pr[[4]], type = "b", pch = 4, lty = 4)
lines(xi, Pr[[5]], type = "b", pch = 5, lty = 5)
lines(xi, Pr[[6]], type = "b", pch = 6, lty = 6)
lines(xi, Pr[[7]], type = "b", pch = 7, lty = 7)

legend("topright",
       legend = c("h=100", "h=10", "h=2", "h=1", "h=1/2", "h=1/10", "h=1/100"),
       pch = c(1, 2, 3, 4, 5, 6, 7),
       lty = c(1, 2, 3, 4, 5, 6, 7),
       col = c("black", "black", "black", "black", "black"),
       bty = "n")

dev.off()

 
  

```